name: Playwright Tests
on:
  push:
    branches:
      - main
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.42.0-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'
      - name: Install dependencies & run tests
        run: |
          pip install pipenv
          pipenv install
          pipenv shell
          pytest --headed
        env:
          HOME: /root
